name: Main pull request workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  Init:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.env_init.outputs.VERSION }}
      PACK_NAME: ${{ steps.env_init.outputs.PACK_NAME }}
    steps:
      - name: Branch Protection
        uses: kirylzhan-stack/cicd-repo/.github/actions/branch-protection@main
        with:
          GH_TOKEN: ${{ secrets.ACCESS_PAT }}
          REPO: ${{ github.repository }}

  Build-and-Test:
    needs: Init
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test Action
        uses: kirylzhan-stack/cicd-repo/.github/actions/build-and-test@main
        with:
          VERSION: ${{ needs.Init.outputs.VERSION }}

  E2E-Tests:
    runs-on: ubuntu-latest
    needs: Build-and-Test
    if: contains(github.event.pull_request.labels.*.name, 'verify')
    steps:
      - name: E2E tests
        uses: kirylzhan-stack/cicd-repo/.github/actions/e2e-tests@main

  Publish-Precheck:
    runs-on: ubuntu-latest
    needs: Build-and-Test
    if: contains(github.event.pull_request.labels.*.name, 'publish')
    steps:
      - name: publish
        uses: kirylzhan-stack/cicd-repo/.github/actions/publish@main
