name: Main PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Protection
        uses: kirylzhan-stack/cicd-repo/.github/actions/branch-protection@main
        with:
          GH_TOKEN: ${{ secrets.ACCESS_PAT }}
          REPO: ${{ github.repository }}

  Build-and-Test:
    needs: Init
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test Action
        uses: kirylzhan-stack/cicd-repo/.github/actions/build-and-test@main

  E2E-Tests:
    runs-on: ubuntu-latest
    needs: Build-and-Test
    if: contains(github.event.pull_request.labels.*.name, 'verify')
    steps:
      - name: E2E tests
        uses: kirylzhan-stack/cicd-repo/.github/actions/e2e-tests@main

  Publish-Precheck:
    runs-on: ubuntu-latest
    needs: [Build-and-Test, E2E-Tests]
    if: |
      always() && 
      needs.Build-and-Test.result == 'success' && 
      (needs.E2E-Tests.result == 'success' || needs.E2E-Tests.result == 'skipped') && 
      contains(github.event.pull_request.labels.*.name, 'publish')
    steps:
      - name: publish
        uses: kirylzhan-stack/cicd-repo/.github/actions/publish@main
        with:
          GH_TOKEN: ${{ secrets.ACCESS_PAT }}
          REPO: ${{ github.repository }}
